# .github/workflows/example_workflow.yml
name: Successful Deploy Action Example
on: deployment_status
jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: XYZ
        run: echo ${DEPLOY_URL}
        env:
          DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
