# .github/workflows/example_workflow.yml
name: Successful Deploy Action Example
on: deployment_status
jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@v1.1.0
        with:
          url: ${{ github.event.deployment_status.target_url }}
      - uses: actions/upload-artifact@v2
        with:
          path: screenshots
          name: Download-screenshots
